# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - master
      - develop
  paths:
    exclude:
      - .editorconfig
      - README.md
      - stylecop.json

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  buildVersion: '0.0.0'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $projVersion = ([xml](Get-Content ".\Net.Http.WebApi.OData\Net.Http.WebApi.OData.csproj")) | Select-Xml -XPath "//Project/PropertyGroup[1]/Version"

      Write-Host "##vso[task.setvariable variable=buildVersion]$projVersion"

- script: dotnet pack ".\Net.Http.WebApi.OData\Net.Http.WebApi.OData.csproj" -o:$(Build.ArtifactStagingDirectory) -p:PackageVersion="$(buildVersion)-preview$(Build.BuildNumber)"
  displayName: 'dotnet pack (pre)'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))

- script: dotnet pack ".\Net.Http.WebApi.OData\Net.Http.WebApi.OData.csproj" -o:$(Build.ArtifactStagingDirectory) -p:PackageVersion=$(buildVersion)
  displayName: 'dotnet pack'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet.org (Net.Http.OData)'
