//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net.Http.WebApi.OData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Net.Http.WebApi.OData.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;day&apos; function is not supported by this service..
        /// </summary>
        internal static string DayFunctionNotSupported {
            get {
                return ResourceManager.GetString("DayFunctionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;endswith&apos; function is not supported by this service..
        /// </summary>
        internal static string EndsWithFunctionNotSupported {
            get {
                return ResourceManager.GetString("EndsWithFunctionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The $filter query option is not supported by this service..
        /// </summary>
        internal static string FilterQueryOptionNotSupported {
            get {
                return ResourceManager.GetString("FilterQueryOptionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The $format query option is not supported by this service..
        /// </summary>
        internal static string FormatQueryOptionNotSupported {
            get {
                return ResourceManager.GetString("FormatQueryOptionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The $inlinecount query option is not supported by this service..
        /// </summary>
        internal static string InlineCountQueryOptionNotSupported {
            get {
                return ResourceManager.GetString("InlineCountQueryOptionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If specified, the $inlinecount value must be either &apos;allpages&apos; or &apos;none&apos;..
        /// </summary>
        internal static string InlineCountRawValueInvalid {
            get {
                return ResourceManager.GetString("InlineCountRawValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;length&apos; function is not supported by this service..
        /// </summary>
        internal static string LengthFunctionNotSupported {
            get {
                return ResourceManager.GetString("LengthFunctionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;month&apos; function is not supported by this service..
        /// </summary>
        internal static string MonthFunctionNotSupported {
            get {
                return ResourceManager.GetString("MonthFunctionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If specified, the $orderby direction must be either &apos;asc&apos; or &apos;desc&apos;..
        /// </summary>
        internal static string OrderByPropertyRawValueInvalid {
            get {
                return ResourceManager.GetString("OrderByPropertyRawValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The $orderby query option is not supported by this service..
        /// </summary>
        internal static string OrderByQueryOptionNotSupported {
            get {
                return ResourceManager.GetString("OrderByQueryOptionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;round&apos; function is not supported by this service..
        /// </summary>
        internal static string RoundFunctionNotSupported {
            get {
                return ResourceManager.GetString("RoundFunctionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The $select query option is not supported by this service..
        /// </summary>
        internal static string SelectQueryOptionNotSupported {
            get {
                return ResourceManager.GetString("SelectQueryOptionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The $skip query option is not supported by this service..
        /// </summary>
        internal static string SkipQueryOptionNotSupported {
            get {
                return ResourceManager.GetString("SkipQueryOptionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If specified, the $skip value must be a positive integer..
        /// </summary>
        internal static string SkipRawValueInvalid {
            get {
                return ResourceManager.GetString("SkipRawValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;startswith&apos; function is not supported by this service..
        /// </summary>
        internal static string StartsWithFunctionNotSupported {
            get {
                return ResourceManager.GetString("StartsWithFunctionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;substringof&apos; function is not supported by this service..
        /// </summary>
        internal static string SubstringOfFunctionNotSupported {
            get {
                return ResourceManager.GetString("SubstringOfFunctionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;tolower&apos; function is not supported by this service..
        /// </summary>
        internal static string ToLowerFunctionNotSupported {
            get {
                return ResourceManager.GetString("ToLowerFunctionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The $top query option is not supported by this service..
        /// </summary>
        internal static string TopQueryOptionNotSupported {
            get {
                return ResourceManager.GetString("TopQueryOptionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If specified, the $top value must be a positive integer..
        /// </summary>
        internal static string TopRawValueInvalid {
            get {
                return ResourceManager.GetString("TopRawValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified $top value exceeds the maximum allowed value of &apos;{0}&apos;.
        /// </summary>
        internal static string TopValueExceedsMaxAllowed {
            get {
                return ResourceManager.GetString("TopValueExceedsMaxAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;toupper&apos; function is not supported by this service..
        /// </summary>
        internal static string ToUpperFunctionNotSupported {
            get {
                return ResourceManager.GetString("ToUpperFunctionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;trim&apos; function is not supported by this service..
        /// </summary>
        internal static string TrimFunctionNotSupported {
            get {
                return ResourceManager.GetString("TrimFunctionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query option &apos;{0}&apos; is not a valid query option. Valid query options are $expand, $filter, $format, $inlinecount, $orderby, $select, $skip, $skiptoken and $top.
        /// </summary>
        internal static string UnknownQueryOption {
            get {
                return ResourceManager.GetString("UnknownQueryOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;year&apos; function is not supported by this service..
        /// </summary>
        internal static string YearFunctionNotSupported {
            get {
                return ResourceManager.GetString("YearFunctionNotSupported", resourceCulture);
            }
        }
    }
}
